#!/bin/bash

cd /home/jcszamosi/MyProjects/COVID19/VaxTrack
Rscript -e "rmarkdown::render('VaxTrack.Rmd','html_document',output_file='index.html')"
Rscript -e "rmarkdown::render('VaxTrackAB.Rmd','html_document',output_file='AB.html')"
Rscript -e "rmarkdown::render('VaxTrackBC.Rmd','html_document',output_file='BC.html')"
Rscript -e "rmarkdown::render('VaxTrackMB.Rmd','html_document',output_file='MB.html')"
Rscript -e "rmarkdown::render('VaxTrackNB.Rmd','html_document',output_file='NB.html')"
Rscript -e "rmarkdown::render('VaxTrackNL.Rmd','html_document',output_file='NL.html')"
Rscript -e "rmarkdown::render('VaxTrackNS.Rmd','html_document',output_file='NS.html')"
Rscript -e "rmarkdown::render('VaxTrackNT.Rmd','html_document',output_file='NT.html')"
Rscript -e "rmarkdown::render('VaxTrackNU.Rmd','html_document',output_file='NU.html')"
Rscript -e "rmarkdown::render('VaxTrackON.Rmd','html_document',output_file='ON.html')"
Rscript -e "rmarkdown::render('VaxTrackPE.Rmd','html_document',output_file='PE.html')"
Rscript -e "rmarkdown::render('VaxTrackQC.Rmd','html_document',output_file='QC.html')"
Rscript -e "rmarkdown::render('VaxTrackSK.Rmd','html_document',output_file='SK.html')"
Rscript -e "rmarkdown::render('VaxTrackYT.Rmd','html_document',output_file='YT.html')"
# git add VaxTrack*.html
# git ct -m "cron autoupdate $(date +%Y-%m-%d)"
# git po
